# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "MIT App Inventor Summit 2019"
subtitle: "Celebrating 10 years of computational action"
email: summit-2019@appinventor.mit.edu
description: >- # this means to ignore newlines until "baseurl:"
  The MIT App Inventor Summit is the annual gathering of the
  world-wide App Inventor community. Hosted by the MIT Computer
  Science and Artificial Intelligence Laboratory (CSAIL).
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://summit.appinventor.mit.edu" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mitappinventor
github_username:  mit-cml
facebook_username: MITAppInventor

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

header_pages:
  - 10-dates.md
  - 20-calls.md
  - 30-attending.md
  - 40-program.md
  - 50-organization.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
